### PR TITLE
Activate tab with first error field on edit a task

### PR DESCRIPTION
**Pull request by yurabakhtin**
Issue: https://github.com/humhub/tasks/issues/169

### CODE REVIEW

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@yurabakhtin Thanks, would it be useful to add something like that to the core?

**Comment by yurabakhtin** [comment]
@luke- 

> would it be useful to add something like that to the core?

Currently the tabs form is rendered by widget:

```php
<?= Tabs::widget([
    'viewPath' => '@tasks/views/task',
    'params' => ['form' => $form, 'taskForm' => $taskForm],
    'items' => $taskForm->getTabs(),
]); ?>
```

If we will implement a new param `'form' => $taskForm` for the core widget `\humhub\widgets\Tabs` and create an interface like `TabbedForm` in order to implement it for the task class `\humhub\modules\tasks\models\forms\TaskForm`.
Then on init the core widget `\humhub\widgets\Tabs` we could get `items` from method of the new param `form` like `$tabbedForm->getTabs()` and there we also could activate first tab with error field as it is currently implemented inside the `TaskForm->getTabs()`.

So answer is yes we can add the useful code to the core.

**Comment by luke-** [comment]
@yurabakhtin Ok, then if you have time, please create a PR for the Core. Please add some example code in the class header.

**Comment by yurabakhtin** [comment]
@luke- 

> Ok, then if you have time, please create a PR for the Core. Please add some example code in the class header.

Core PR https://github.com/humhub/humhub/pull/5472.
Changes for this module - https://github.com/humhub/tasks/pull/175.

**Comment by luke-** [comment]
@yurabakhtin Thanks, I've commtend the PRs.

**Pull request merged**
