### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by yurabakhtin**
Issue: https://github.com/humhub/team_tasks/issues/218

### CODE REVIEW

**Comment by luke-** [comment]
@yurabakhtin Maybe we can reduce the Translation message categories? Mainly base etc.?

**Comment by yurabakhtin** [comment]
@luke- 

> Maybe we can reduce the Translation message categories? Mainly base etc.?

Do you mean to replace in all places to `Yii::t('TasksModule.base', ...` for this module?

**Comment by luke-** [comment]
@yurabakhtin Yes, Unless there are other meaningful distinctions. Atm the tests are broken?

**Comment by yurabakhtin** [comment]
@luke- 

> Atm the tests are broken?

Same answer here https://github.com/humhub/calendar/pull/318#issuecomment-1157196709.

**Comment by yurabakhtin** [comment]
@luke- 

> Yes, Unless there are other meaningful distinctions.

If we will replace all strings then is it possible to move all strings from other category language files to the base file?
I mean some automatic way instead of manual, otherwise all previous translations will be lost.

**Comment by luke-** [comment]
@yurabakhtin Ok, go ahead with one .base category. We need to reduce the file count a bit :-)

**Comment by yurabakhtin** [comment]
@luke- It is fast to replace the categories of all strings, but please see what I mean in my question above, so is it normal if all previous translations will be lost, or do you know some fast way to move all previous translations into the base file?

question

**Comment by luke-** [comment]
@yurabakhtin Please try the https://github.com/humhub/translation module. There should be CLI commands for rename categories.

**Comment by yurabakhtin** [comment]
@luke- Thanks, the module "Translation" helps to move strings, but please note not all languages were processed:

- br
- en-GB
- fa_ir
- nb_no
- nn_no
- pt_br
- zh_cn
- zh_tw

I think because they are not active in system, and I could not find a way how to add them into the list `http://stie.test/translation-manager/admin/languages`.

Commit https://github.com/humhub/tasks/pull/187/commits/531de23b07e2093de987034251aeb5ab090632b0

**Pull request merged**
